[theme]
base = "light"
primaryColor = "#087F8C"
backgroundColor = "#F7FAFC"
secondaryBackgroundColor = "#EAF3F5"
textColor = "#183247"
font = "sans-serif"

baseFontSize = 18
headingFontSizes = ["3rem", "2.4rem", "1.9rem"]
metricValueFontSize = "2.75rem"
